// ═══════════════════════════════════════════════════════════════
// Netsyra IDE — Monaco Theme (VS Code Dark+ exact replica)
// ═══════════════════════════════════════════════════════════════

import type { Monaco } from "@monaco-editor/react";

export const NETSYRA_THEME = "netsyra-dark";

export function defineNetsyraTheme(monaco: Monaco): void {
  monaco.editor.defineTheme(NETSYRA_THEME, {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "comment", foreground: "6a9955", fontStyle: "italic" },
      { token: "keyword", foreground: "569cd6" },
      { token: "keyword.control", foreground: "c586c0" },
      { token: "keyword.operator", foreground: "d4d4d4" },
      { token: "string", foreground: "ce9178" },
      { token: "string.escape", foreground: "d7ba7d" },
      { token: "number", foreground: "b5cea8" },
      { token: "regexp", foreground: "d16969" },
      { token: "type", foreground: "4ec9b0" },
      { token: "type.identifier", foreground: "4ec9b0" },
      { token: "class", foreground: "4ec9b0" },
      { token: "interface", foreground: "4ec9b0" },
      { token: "namespace", foreground: "4ec9b0" },
      { token: "function", foreground: "dcdcaa" },
      { token: "variable", foreground: "9cdcfe" },
      { token: "variable.predefined", foreground: "569cd6" },
      { token: "variable.parameter", foreground: "9cdcfe" },
      { token: "constant", foreground: "4fc1ff" },
      { token: "constant.numeric", foreground: "b5cea8" },
      { token: "property", foreground: "9cdcfe" },
      { token: "enum", foreground: "4ec9b0" },
      { token: "decorator", foreground: "dcdcaa" },
      { token: "tag", foreground: "569cd6" },
      { token: "attribute.name", foreground: "9cdcfe" },
      { token: "attribute.value", foreground: "ce9178" },
      { token: "delimiter", foreground: "d4d4d4" },
      { token: "delimiter.bracket", foreground: "d4d4d4" },
      { token: "delimiter.parenthesis", foreground: "d4d4d4" },
      { token: "identifier", foreground: "d4d4d4" },
      { token: "operator", foreground: "d4d4d4" },
    ],
    colors: {
      "editor.background": "#1e1e1e",
      "editor.foreground": "#d4d4d4",
      "editorLineNumber.foreground": "#858585",
      "editorLineNumber.activeForeground": "#c6c6c6",
      "editorCursor.foreground": "#aeafad",
      "editor.selectionBackground": "#264f78",
      "editor.inactiveSelectionBackground": "#3a3d41",
      "editor.selectionHighlightBackground": "#264f78aa",
      "editor.selectionHighlightBorder": "#264f78",
      "editor.lineHighlightBackground": "#ffffff0d",
      "editor.lineHighlightBorder": "#282828",
      "editorIndentGuide.background": "#404040",
      "editorIndentGuide.activeBackground": "#707070",
      "editorBracketMatch.background": "#0064001a",
      "editorBracketMatch.border": "#888",
      "editorGutter.background": "#1e1e1e",
      "editorGutter.modifiedBackground": "#e2c08d",
      "editorGutter.addedBackground": "#81b88b",
      "editorGutter.deletedBackground": "#ca4b51",
      "editorError.foreground": "#f48771",
      "editorError.background": "#f4877119",
      "editorWarning.foreground": "#cca700",
      "editorWarning.background": "#cca70019",
      "editorInfo.foreground": "#75beff",
      "editorHint.foreground": "#888",
      "editorOverviewRuler.border": "#00000000",
      "editorOverviewRuler.errorForeground": "#f48771cc",
      "editorOverviewRuler.warningForeground": "#cca700cc",
      "editorOverviewRuler.infoForeground": "#75beffcc",
      "editor.findMatchBackground": "#515c6a",
      "editor.findMatchHighlightBackground": "#ea5c004d",
      "editor.findRangeHighlightBackground": "#3a3d4155",
      "editor.linkedEditingBackground": "#a0a0a033",
      "editor.wordHighlightBackground": "#464646bb",
      "editor.wordHighlightStrongBackground": "#6e6e6e88",
      "editor.hoverHighlightBackground": "#264f7840",
      "editor.rangeHighlightBackground": "#264f7840",
      "editor.symbolHighlightBackground": "#46464640",
      "editorWhitespace.foreground": "#e3e4e229",
      "editorUnnecessaryCode.opacity": "#000000aa",
      "editorBracketHighlight.foreground1": "#ffd700",
      "editorBracketHighlight.foreground2": "#da70d6",
      "editorBracketHighlight.foreground3": "#179fff",
      "editorBracketHighlight.unexpectedBracket.foreground": "#f48771",
      "editorBracketPairGuide.activeBackground1": "#ffd70066",
      "editorBracketPairGuide.activeBackground2": "#da70d666",
      "editorBracketPairGuide.activeBackground3": "#179fff66",
      "editorBracketPairGuide.background1": "#ffd70022",
      "editorBracketPairGuide.background2": "#da70d622",
      "editorBracketPairGuide.background3": "#179fff22",
      "editor.foldBackground": "#ffffff0d",
      "editor.focusBorder": "#007acc",
      "editorPane.background": "#1e1e1e",
      "editorGutter.commentRangeForeground": "#c5c5c5",
      "editorWidget.background": "#252526",
      "editorWidget.border": "#454545",
      "editorSuggestWidget.background": "#252526",
      "editorSuggestWidget.border": "#454545",
      "editorSuggestWidget.foreground": "#d4d4d4",
      "editorSuggestWidget.focusBackground": "#062f4a",
      "editorSuggestWidget.highlightForeground": "#0097fb",
      "editorSuggestWidget.selectedBackground": "#062f4a",
      "editorHoverWidget.background": "#252526",
      "editorHoverWidget.border": "#454545",
      "editorGhostText.foreground": "#ffffff56",
      "editorStickyScroll.background": "#1e1e1e",
      "editorStickyScroll.border": "#3c3c3c",
      "editorStickyScroll.shadow": "#00000066",
      "scrollbar.shadow": "#00000000",
      "scrollbarSlider.background": "#79797966",
      "scrollbarSlider.hoverBackground": "#646464b3",
      "scrollbarSlider.activeBackground": "#bfbfbf66",
      "minimap.background": "#1e1e1e",
      "minimapSlider.background": "#79797966",
      "minimapSlider.hoverBackground": "#646464b3",
      "minimapSlider.activeBackground": "#bfbfbf66",
      "minimapGutter.addedBackground": "#81b88b",
      "minimapGutter.modifiedBackground": "#e2c08d",
      "minimapGutter.deletedBackground": "#ca4b51",
      "minimapErrorHighlight": "#f48771",
      "minimapWarningHighlight": "#cca700",
      "minimapFindMatchHighlight": "#515c6a",
      "minimapSelectionHighlight": "#264f78",
      "editor.selectionForeground": "#ffffff",
      "focusBorder": "#007acc",
      "foreground": "#cccccc",
      "descriptionForeground": "#cccccc",
      "errorForeground": "#f48771",
      "selection.background": "#264f78",
      "icon.foreground": "#c5c5c5",
      "input.background": "#3c3c3c",
      "input.border": "#3c3c3c",
      "input.foreground": "#cccccc",
      "input.placeholderForeground": "#a6a6a6",
    },
  });
}
